# Generated by Django 3.1 on 2020-08-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='create_time')),
                ('update_time', models.DateTimeField(verbose_name='update_time')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_ids', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='create_time')),
                ('update_time', models.DateTimeField(verbose_name='update_time')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_monitor.api')),
            ],
        ),
    ]
