# Generated by Django 3.1 on 2020-08-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='api_ids',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='api',
        ),
        migrations.AddField(
            model_name='monitor',
            name='api',
            field=models.ManyToManyField(to='api_monitor.API'),
        ),
    ]
