# Generated by Django 3.1 on 2020-08-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0002_auto_20200826_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='api',
            new_name='api_id',
        ),
    ]
