# Generated by Django 3.1 on 2020-08-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0005_auto_20200826_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.BigIntegerField()),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('time_line', models.TimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('api_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_monitor.api')),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
