# Generated by Django 3.1 on 2020-08-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0008_auto_20200827_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='query',
            new_name='params',
        ),
    ]
