# Generated by Django 3.1 on 2020-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0009_auto_20200827_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='body',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='params',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
