# Generated by Django 3.1 on 2020-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0010_auto_20200831_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='headers',
            field=models.CharField(blank=True, help_text='使用dict类型，例如：{"key":"value"}', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='body',
            field=models.CharField(blank=True, help_text='使用dict类型，例如：{"key":"value"}', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(help_text='填写请求类型，例如：POST', max_length=200),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=200),
        ),
        migrations.AlterField(
            model_name='api',
            name='params',
            field=models.CharField(blank=True, help_text='使用dict类型，例如：{"key":"value"}', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(help_text='填写url地址，例如：https://api-primary-test.yangcong345.com/primary_account/classCourse/class/getGrade', max_length=200),
        ),
    ]
